CREATE TABLE defaultdb.Users (
	UserID varchar(100) NOT NULL UNIQUE,
	GitHubUsername varchar(100) NOT NULL,
	CreateTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	LastUpdateTimestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT Users_PK PRIMARY KEY (UserID)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci
AUTO_INCREMENT=1;
