name: Build Beta Docker Image

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build & Push Docker Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set BUILD_TAG Variable
        id: buildTag
        run: echo "BUILD_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            "ghcr.io/${{ github.repository_owner }}/bot:${{ github.RUN_ID }}"
            "ghcr.io/${{ github.repository_owner }}/bot:beta"

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: 'If successful, the new latest image is ${{ github.RUN_ID }}'
